version: "3"

services:
    db:
        container_name: postgres_database
        image: postgres:15.1
        volumes:
            #CASO 1 - VOLUMEN
            # - postgres-db:/var/lib/postgresql/data
            - ./postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    pgAdmin:
        depends_on:
            - db
        image: dpage/pgadmin4:6.17
        ports:
            - "8080:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}

#CASO 1 - VOLUMEN
# volumes:
#     postgres-db:
#         external: true
